"""Spark Batch job to compute technical features from processed data."""
import sys
from datetime import datetime, timedelta
from pyspark.sql import SparkSession
from pyspark.sql.window import Window
from pyspark.sql.functions import col, avg, stddev, log, lag, when, sum
from loguru import logger

def create_spark_session():
    return SparkSession.builder \
        .appName("FeatureEngineering") \
        .config("spark.executor.memory", "1g") \
        .config("spark.driver.memory", "1g") \
        .getOrCreate()

def calculate_rsi(df, period=14):
    """Calculate Relative Strength Index."""
    window_spec = Window.partitionBy("symbol").orderBy("window_start")

    # Calculate price change
    df = df.withColumn("change", col("close") - lag("close", 1).over(window_spec))

    # Separate gains and losses
    df = df.withColumn("gain", when(col("change") > 0, col("change")).otherwise(0.0))
    df = df.withColumn("loss", when(col("change") < 0, -col("change")).otherwise(0.0))

    # Calculate average gain and loss (using simple moving average for simplicity in Spark SQL)
    window_rsi = Window.partitionBy("symbol").orderBy("window_start").rowsBetween(-period + 1, 0)
    df = df.withColumn("avg_gain", avg("gain").over(window_rsi))
    df = df.withColumn("avg_loss", avg("loss").over(window_rsi))

    # Calculate RS and RSI
    df = df.withColumn("rs", col("avg_gain") / when(col("avg_loss") == 0, 1.0).otherwise(col("avg_loss")))
    df = df.withColumn("rsi", when(col("avg_loss") == 0, 100.0).otherwise(100.0 - (100.0 / (1.0 + col("rs")))))

    return df.drop("change", "gain", "loss", "avg_gain", "avg_loss", "rs")

def calculate_macd(df, fast=12, slow=26, signal=9):
    """Calculate Moving Average Convergence Divergence."""
    window_fast = Window.partitionBy("symbol").orderBy("window_start").rowsBetween(-fast + 1, 0)
    window_slow = Window.partitionBy("symbol").orderBy("window_start").rowsBetween(-slow + 1, 0)

    df = df.withColumn("ema_fast", avg("close").over(window_fast))
    df = df.withColumn("ema_slow", avg("close").over(window_slow))
    df = df.withColumn("macd", col("ema_fast") - col("ema_slow"))

    window_signal = Window.partitionBy("symbol").orderBy("window_start").rowsBetween(-signal + 1, 0)
    df = df.withColumn("macd_signal", avg("macd").over(window_signal))
    df = df.withColumn("macd_hist", col("macd") - col("macd_signal"))

    return df.drop("ema_fast", "ema_slow")

def calculate_bollinger_bands(df, period=20, std_dev=2):
    """Calculate Bollinger Bands."""
    window_bb = Window.partitionBy("symbol").orderBy("window_start").rowsBetween(-period + 1, 0)

    df = df.withColumn("bb_middle", avg("close").over(window_bb))
    df = df.withColumn("stddev", stddev("close").over(window_bb))

    df = df.withColumn("bb_upper", col("bb_middle") + (col("stddev") * std_dev))
    df = df.withColumn("bb_lower", col("bb_middle") - (col("stddev") * std_dev))

    return df.drop("stddev")

def calculate_momentum(df, hours=[1, 4, 24]):
    """Calculate price momentum over various horizons (assuming 1-min data)."""
    for h in hours:
        periods = h * 60
        window_mom = Window.partitionBy("symbol").orderBy("window_start")
        df = df.withColumn(f"mom_{h}h",
            (col("close") - lag("close", periods).over(window_mom)) / lag("close", periods).over(window_mom) * 100)
    return df

def calculate_volume_ma(df, days=7):
    """7-day rolling average volume (assuming 1-min data)."""
    periods = days * 24 * 60
    window_vol = Window.partitionBy("symbol").orderBy("window_start").rowsBetween(-periods + 1, 0)
    df = df.withColumn("vol_ma_7d", avg("avg_volume").over(window_vol))
    return df

def main():
    spark = create_spark_session()

    processed_path = "/opt/airflow/data/processed/ohlcv"
    features_path = "/opt/airflow/data/features/ohlcv"

    logger.info("Starting feature engineering...")

    try:
        df = spark.read.parquet(processed_path)
    except Exception as e:
        logger.error(f"Failed to read processed data: {e}")
        sys.exit(1)

    if df.rdd.isEmpty():
        logger.warning("No data available for feature engineering. Exiting.")
        sys.exit(0)

    # Compute features
    logger.info("Calculating RSI...")
    df = calculate_rsi(df)

    logger.info("Calculating MACD...")
    df = calculate_macd(df)

    logger.info("Calculating Bollinger Bands...")
    df = calculate_bollinger_bands(df)

    logger.info("Calculating Momentum...")
    df = calculate_momentum(df)

    logger.info("Calculating Volume Moving Average...")
    df = calculate_volume_ma(df)

    # Drop any nulls generated by window functions for initial periods
    df = df.dropna()

    # Write features to parquet
    df.write \
        .mode("overwrite") \
        .partitionBy("symbol", "date") \
        .parquet(features_path)

    logger.info(f"Successfully computed and wrote features to {features_path}")
    spark.stop()

if __name__ == "__main__":
    main()
